output-format: grouped
strictness: veryhigh
doc-warnings: true
test-warnings: false

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true

pylint:
  run: true
  disable:
    - bad-builtin
    # Line length is check py Flake8.
    - line-too-long
    - missing-docstring
    - star-args
    - superfluous-parens
    - too-few-public-methods
    - wrong-import-order

pep8:
  run: true
  disable:
    - E126

pep257:
  run: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D203
    - D213
    - D400
    - D401
    - D404

pyflakes:
  run: true

pyroma:
  run: true
