language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script:
  - nosetests --with-coverage --cover-package="data_mine" --verbosity=2

# Push the results back to codecov
after_success:
  - codecov
